// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LocateFolder
{
    static class Vsix
    {
        public const string Id = "106f5189-471d-40ab-9de2-687c0a3d98e4";
        public const string Name = "LocateFolder";
        public const string Description = @"Helps to locate files and folder in windows explorer.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Akhil Mittal";
        public const string Tags = "file locator, folder locator, open file in explorer";
    }
}
