// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LocateFolder
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidLocateFolderCommandPackageString = "a7836cc5-740b-4d5a-8a94-dc9bbc4f7db1";
        public const string guidLocateFolderCommandPackageCmdSetString = "031046af-15f9-44ab-9b2a-3f6cad1a89e3";
        public const string guidImagesString = "8ac8d2e1-5ef5-4ad7-8aa6-84da2268566a";
        public static Guid guidLocateFolderCommandPackage = new Guid(guidLocateFolderCommandPackageString);
        public static Guid guidLocateFolderCommandPackageCmdSet = new Guid(guidLocateFolderCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int LocateFolderCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
